CREATE DATABASE IF NOT EXISTS crowdview;
USE crowdview;

CREATE TABLE IF NOT EXISTS User (
  User_Id INT AUTO_INCREMENT PRIMARY KEY,
  Email VARCHAR(255) NOT NULL UNIQUE,
  Password_Hash VARCHAR(255) NOT NULL,
  Name_Txt VARCHAR(100),
  Last_Source_Device_Id VARCHAR(255),
  Connect_Last_Used_Device_After_Login_Fl CHAR(1) DEFAULT 'N',
  Facebook_Token TEXT,
  Instagram_Token TEXT,
  YouTube_Token TEXT,
  User_Level INT DEFAULT 0,
  Password_Reset_Token VARCHAR(255),
  Password_Reset_Expires DATETIME,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Friend (
  Friend_Id INT AUTO_INCREMENT PRIMARY KEY,
  User_Id INT NOT NULL,
  Name_Txt VARCHAR(100) NOT NULL,
  Note_Multi_Line_Txt TEXT,
  Friend_Group VARCHAR(50) DEFAULT 'Friend',
  Friend_User_Id INT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (User_Id) REFERENCES User(User_Id) ON DELETE CASCADE,
  FOREIGN KEY (Friend_User_Id) REFERENCES User(User_Id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Friend_Photo (
  Friend_Photo_Id INT AUTO_INCREMENT PRIMARY KEY,
  Friend_Id INT NOT NULL,
  Photo_Data LONGBLOB NOT NULL,
  Photo_Mime_Type VARCHAR(50) DEFAULT 'image/jpeg',
  Rekognition_Face_Id VARCHAR(255) NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Friend_Id) REFERENCES Friend(Friend_Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS User_Media (
  User_Media_Id INT AUTO_INCREMENT PRIMARY KEY,
  User_Id INT NOT NULL,
  Media_Data LONGBLOB NOT NULL,
  Media_Mime_Type VARCHAR(50),
  Media_Type ENUM('photo', 'video') NOT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (User_Id) REFERENCES User(User_Id) ON DELETE CASCADE
);
